on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.20'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'

name: Release Binaries pmmp 3

jobs:
  build-php:
    name: Building cross compiler for android-aarch64
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: true
      matrix:
          include:
            - option: "-g"
              name: "-8.0"
              branch: "stable"
            - option: "-g"
              name: "-8.1"
              branch: "php/8.1"
            # Please note that if editing the matrix, the release workflow must also be edited.
    steps:
      - uses: actions/checkout@v2
        with:
         repository: pmmp/php-build-scripts
         path: php-build-scripts
         ref: ${{ matrix.branch }}

      - name: install module
        run: |
          sudo apt update &> /dev/null
          sudo apt install -y re2c libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev &> /dev/null
          
      - name: making aarch64 php
        working-directory: php-build-scripts
        run: ./compile.sh ${{ matrix.option }} -t linux64 -j4 -f x86_64
        
        # https://doc.pmmp.io/en/rtfd/faq/installation/opcache.so.html
      - name: fix opcache warning
        working-directory: php-build-scripts
        run: |
          EXTENSION_DIR=$(find "$(pwd)/bin" -name "*debug-zts*")
          grep -q '^extension_dir' bin/php7/bin/php.ini && sed -i'bak' "s{^extension_dir=.*{extension_dir=\"$EXTENSION_DIR\"{" bin/php7/bin/php.ini || echo "extension_dir=\"$(realpath -m -q --relative-to="$(pwd)" $EXTENSION_DIR)\"" >> bin/php7/bin/php.ini

      - name: file compressions
        working-directory: php-build-scripts
        run: | 
          zip -r -9 bin.zip bin > /dev/null

      - name: copy compressed bin
        run: |
          mv ./php-build-scripts/bin.zip bin${{ matrix.name }}.zip

      - name: echo sha256sum
        run: sha256sum "bin${{ matrix.name }}.zip"
      - uses: actions/upload-artifact@v1
        with:
          name: "bin${{ matrix.name }}.zip"
          path: "bin${{ matrix.name }}.zip"
          

  commit-php:
    name: release
    needs: build-php
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.createRelease == 'yes'}}
    steps:
      - name: Download a Build Artifact(bin-8.0.zip)
        uses: actions/download-artifact@v2
        with:
          name: bin-8.0.zip

      - name: Download a Build Artifact(bin-8.1.zip)
        uses: actions/download-artifact@v2
        with:
          name: bin-8.1.zip

      - name: create checksums.sha256
        run: |
          sha256sum "bin-8.0.zip" "bin-8.1.zip" > checksums.sha256
          cat checksums.sha256
          
      - uses: actions/upload-artifact@v1
        with:
          name: "checksums.sha256"
          path: "./checksums.sha256"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tagname }}
          name: Release ${{ github.event.inputs.tagname }}
          files: |
            bin-8.0.zip
            bin-8.1.zip
            checksums.sha256
          body: "The php version for this release is ${{ github.event.inputs.tagname }}.

## warning

If using ubuntu 20 or higher os, please use the official binaries.

https://jenkins.pmmp.io/"
